vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: 'img/article'
            #uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/img/article'
            #upload_destination: 'http://PlantShop/public/img/article'
            #upload_destination: '%kernel.project_dir%/public/%uploads_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: false


